# https://travis-ci.org/moeoverflow/Araisan
sudo: false

language: python
os:
    - linux

env:
    global:
        - NEWEST_PYTHON=3.6

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
cache: pip

matrix:
    include:
        # Manually defined OS X builds
        # https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)

        # Stock OSX Python
        - os: osx

        # Latest Python 2.x from Homebrew
        - os: osx
          env: BREW_INSTALL=python

        # Latest Python 3.x from Homebrew
        - os: osx
          env: BREW_INSTALL=python3

        # Python Codestyle
        - os: linux
          python: 3.6
          env: CODESTYLE=true

install:
    - |
        if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
            if [[ -n "$BREW_INSTALL" ]]; then
                brew update
                brew install "$BREW_INSTALL"
            fi
            sudo pip install pyyaml
        fi
        if [[ $CODESTYLE ]]; then
            pip install pycodestyle
        fi
script:
    - |
        if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
            if [[ $CODESTYLE ]]; then
                # 241 - multiple spaces after ‘,’
                # 501 - line too long
                # 711 - comparison to None should be 'if cond is not None:'
                pycodestyle --ignore=E241,E501,E711
            else
                make
            fi
        fi

after_success:
    - |
        if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON && $TRAVIS_OS_NAME == 'linux' ]]; then
            pip install python-coveralls && coveralls
        fi
